### ISSUE TITLE
MAUI App failed to start

### ISSUE THREAD

**Issue by samhouts** [BretJohnson/aspire-mobile#43]
I followed the instructions to add to an existing MAUI project. Upon running the AppHost, everything starts except for the maui client.

```
Failed to create resource mauiclient
System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> Aspire.Hosting.ApplicationModel.EnvironmentCallbackContext.get_EnvironmentVariables()'.
   at Aspire.Hosting.MobileProjectResourceBuilderExtension.<>c__DisplayClass0_0.<AddMobileProject>b__0(EnvironmentCallbackContext context)
   at Aspire.Hosting.ApplicationModel.EnvironmentCallbackAnnotation.<>c__DisplayClass3_0.<.ctor>b__0(EnvironmentCallbackContext c) in /_/src/Aspire.Hosting/ApplicationModel/EnvironmentCallbackAnnotation.cs:line 59
   at Aspire.Hosting.Dcp.ApplicationExecutor.CreateExecutableAsync(AppResource er, ILogger resourceLogger, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 1182
   at Aspire.Hosting.Dcp.ApplicationExecutor.<CreateExecutablesAsync>g__CreateExecutableAsyncCore|51_0(AppResource cr, CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 1083
```

**Comment by aeges** [comment]
Had the same Issue. I could solve it by [using the latest main CI builds](https://github.com/BretJohnson/aspire-mobile?tab=readme-ov-file#using-the-latest-main-ci-builds).

BTW: I also had to change the method http.UseServiceDiscovery() to http.AddServiceDiscovery() in AppDefaultsExtensions.cs and Extensions.cs to build with latest 8.0.1 release of Aspire.

**Comment by BartNetJS** [comment]
@aeges  I have the same issue. Did the updates like you suggested.
But this is never called:
![image](https://github.com/BretJohnson/aspire-mobile/assets/4865355/366f2fce-3a55-4451-84ac-1471e74ad0a6)
Any idea what's wrong?

**Comment by BartNetJS** [comment]
Fixed it with updating aspireMobile to latest aspire nugets.
I will create a PR for it

**Comment by BartNetJS** [comment]
@BretJohnson I see it is already in this PR: https://github.com/BretJohnson/aspire-mobile/pull/42
Can you approve it?
Tx

**Comment by BretJohnson** [comment]
I updated everything to be consistent with Aspire GA & published the updates to nuget.org. This should all work now. 
@samhouts @BartNetJS @aeges - let me know if you run into more issues or have any other feedback / wish list items

**Comment by BartNetJS** [comment]
@BretJohnson 

In this code snipped:

#if DEBUG
        mauiAppBuilder.Configuration.AddInMemoryCollection(AspireAppSettings.Settings);
#endif

How are the settings loaded in a release build?
